### ISSUE TITLE
Add Non-Linear Causal Relationships

### ISSUE THREAD

**Issue by JohannesHuegle** [hpi-epic/manm-cs#29]
To provide more data characteristics beyond the conditional Gaussian distribution model, MANM-CS should be extended by non-linear causal relationships.

**Comment by ChristopherSchmidt89** [comment]
Currently, we have "Defines the percentage of nodes that shall be of discrete type. Depending on its value the appropriate model (multivariate normal, mixed gaussian, discrete only) is chosen.".
Should non-linear causal relationships exist independent of the model (see quoted sentence)?
Further, do we want to support a mixture of types of relationships?

**Comment by ChristopherSchmidt89** [comment]
As noted from the discussion. We want to remove the beta values for continues to continues variables relationships. And rather have functions e.g., linear, quadratic, power of, tanh, betrag|exp|, ... .

**Comment by JohannesHuegle** [comment]
Proposed Strucuter:- Continuou

**Comment by JohannesHuegle** [comment]
> As noted from the discussion. We want to remove the beta values for continues to continues variables relationships. And rather have functions e.g., linear ( ), ( )², ( )³, tanh( ), sin( ), ... .

Proposed Structure with Parameters: (4 possible models to choose)
- Continuous:
     1. 
- Discrete:

**Comment by JohannesHuegle** [comment]
**Proposed Structure Including Parameters:**

**Overall**
1.	`num_processes`

**Graph Sampling**
1.	`num_nodes`
2.	`edge_density`
3.	`num_samples`

**Distribution Model**

_Continuous_
    1.	List of possible functions from {linear ( ), ( )², ( )³, tanh( ), sin( ), ...}
    2.	Sample probability for each function
    3.	`continuous_noise_std` [0, Inf)

_Discrete_
    1.	`min_discrete_value_classes`
    2.	`max_discrete_value_classes`
    3.	`discrete_signal_to_noise_ratio`

_Conditional Linear Gaussian_
    1.	`discrete_node_ratio`
    2.	`min_discrete_value_classes`
    3.	`max_discrete_value_classes`
    4.	`discrete_signal_to_noise_ratio`
    5.	`continuous_noise_std`
    6.	continuous_beta (tbd)

_Mixed_
    1.	`discrete_node_ratio`
    2.	`min_discrete_value_classes`
    3.	`max_discrete_value_classes`
    4.	List of possible functions from {linear ( ), ( )², ( )³, tanh( ), sin( ), ...}
    5.	Sample probability for each function
    6.	`discrete_signal_to_noise_ratio`
    7.	`continuous_noise_std`
