### ISSUE TITLE
Reliability of edge density

### ISSUE THREAD

**Issue by ChristopherSchmidt89** [hpi-epic/manm-cs#44]
Issue: generated data may not have enough edges
In the following code snippet, edge density is used to generate a directed graph via networkx 
afterward only forward-pointing edges (in terms of indices) are used. Therefore the number of edges in the resulting model can be reduced significantly and the chosen edge density is no longer guaranteed.
https://github.com/hpi-epic/manm-cs/blob/042248799e3d07ba6267c5b67133dd121f5a7331/manm_cs/graph/graph_builder.py#L169-L174

set directed=False and check what else needs changing

**Comment by ChristopherSchmidt89** [comment]
@JohannesHuegle what are your thoughts?

**Comment by JohannesHuegle** [comment]
The above code for generating DAG's provides a reliable edge density, as de resulting DAG has an edge density w.r.t. to an oriented graph, where no 2-cycles are possible, as commonly assumed for DAGs (or an average degree around p acc. to the maximum achievable outdegree).

Note, that nx.density( ) applied to DAGs calculates the edge density according #Edges/(#Nodes * (#Nodes -1)), hence, p/2 for DAGs.
