### ISSUE TITLE
Modularity of parametrization of a model given a graph

### ISSUE THREAD

**Issue by adam2392** [hpi-epic/manm-cs#45]
Hi,

Thanks for this neat package on helping to simulate data from graphical models. I am wondering how easy / is it possible to pass in a fixed graph, and then simulate many random models (i.e. different types of variables on different nodes and different types of edge dependencies), while keeping the graph fixed?

Right now, the `GraphBuilder` object builds both a random graph and a random graphical model given the graph.

Thanks!

**Comment by ChristopherSchmidt89** [comment]
Hi, 
thanks for your interest in our package.
The current version does not support loading a fixed graph, only the seed for graph generation could be fixed. Yet, it should be possible to adjust for loading a pre-defined fixed graph.
I added a short example loading from .gml file (see #46 ) Is that the direction you are thinking about?

**Comment by adam2392** [comment]
Hi @ChristopherSchmidt89 ah yes #46 looks exactly like what I was thinking! That would be great addition. 

For context: I'm running some experiments and am using this package and would like to generate multiple models for the same graph to get a sense of how my proposed algorithm works on this specific graphical structure.

**Comment by ChristopherSchmidt89** [comment]
@adam2392 Sounds great. We adapted the functionality a little from what I suggested (see #46 ). 
`GraphBuilder` now supports loading a graph structure from a networkx.DiGraph() . That way you can create the DiGraph from other input sources, too.
Command line argument is still a file to a .gml

If you encounter any other issues or have suggestions, let us know.
